### PR TITLE
fix(dependencies): require explicitly psr/simple-cache

### PR DESCRIPTION
**Pull request by Gounlaf**
Add dependency to `psr/simple-cache` manually, and force symfony/cache to be < 4.3

### CODE REVIEW

**Comment by natebrunette** [comment]
Changing the minimum version is a breaking change.

**Comment by Gounlaf** [comment]
Current package was allowing symfony 4.0 to 4.x, less than 4.5

Here I just fix the scope to <4.3

The breaking change is done in the other PR (I haven't fixed it correctly so CI failed) where I actually change the minimum version

**Comment by Gounlaf** [comment]
Hi @natebrunette,

To avoid breaking change, I've created a `CacheProvider` class that will provide appropriate class, depending on Symfony version.

The unit tests part is quite ugly now (had to use Reflection)

**Comment by natebrunette** [comment]
What is this fixing?

**Comment by Gounlaf** [comment]
> What is this fixing?

Current composer definitions permit large version of Symfony 4.x
Since 4.3, cache classes has been rewritten - and `psr/simple-cache` need to be required manually.

Since previous commit was a breaking change - you said `Changing the minimum version is a breaking change`, I had to find a way to be compatible with Symfony >= 4.3

**Comment by javadev** [comment]
This branch has conflicts that must be resolved

**Comment by natebrunette** [comment]
resolved with : #43

**Pull request closed without merging**
